"""added user id in review

Revision ID: 48b829769313
Revises: 3e758b818736
Create Date: 2024-11-22 12:54:02.954272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '48b829769313'
down_revision: Union[str, None] = '3e758b818736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue_review', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'venue_review', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue_review', type_='foreignkey')
    op.drop_column('venue_review', 'user_id')
    # ### end Alembic commands ###
