"""added cascading

Revision ID: a235be682844
Revises: bcd4aeedb5ec
Create Date: 2024-11-19 13:52:11.987521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a235be682844'
down_revision: Union[str, None] = 'bcd4aeedb5ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booking_decoration_id_fkey', 'booking', type_='foreignkey')
    op.drop_constraint('booking_promo_id_fkey', 'booking', type_='foreignkey')
    op.drop_constraint('booking_payment_id_fkey', 'booking', type_='foreignkey')
    op.drop_constraint('booking_catering_id_fkey', 'booking', type_='foreignkey')
    op.drop_constraint('booking_user_id_fkey', 'booking', type_='foreignkey')
    op.create_foreign_key(None, 'booking', 'promo', ['promo_id'], ['promo_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'booking', 'catering', ['catering_id'], ['catering_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'booking', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'booking', 'decoration', ['decoration_id'], ['decoration_id'], ondelete='CASCADE')
    op.drop_column('booking', 'payment_id')
    op.drop_constraint('car_reservation_booking_id_fkey', 'car_reservation', type_='foreignkey')
    op.drop_constraint('car_reservation_car_id_fkey', 'car_reservation', type_='foreignkey')
    op.create_foreign_key(None, 'car_reservation', 'booking', ['booking_id'], ['booking_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'car_reservation', 'car', ['car_id'], ['car_id'], ondelete='CASCADE')
    op.drop_constraint('catering_menu_item_dish_id_fkey', 'catering_menu_item', type_='foreignkey')
    op.drop_constraint('catering_menu_item_catering_id_fkey', 'catering_menu_item', type_='foreignkey')
    op.create_foreign_key(None, 'catering_menu_item', 'catering', ['catering_id'], ['catering_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'catering_menu_item', 'dish', ['dish_id'], ['dish_id'], ondelete='CASCADE')
    op.add_column('payment', sa.Column('booking_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'payment', 'booking', ['booking_id'], ['booking_id'], ondelete='CASCADE')
    op.drop_constraint('user_contact_user_id_fkey', 'user_contact', type_='foreignkey')
    op.create_foreign_key(None, 'user_contact', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('venue_review_venue_id_fkey', 'venue_review', type_='foreignkey')
    op.create_foreign_key(None, 'venue_review', 'venue', ['venue_id'], ['venue_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue_review', type_='foreignkey')
    op.create_foreign_key('venue_review_venue_id_fkey', 'venue_review', 'venue', ['venue_id'], ['venue_id'])
    op.drop_constraint(None, 'user_contact', type_='foreignkey')
    op.create_foreign_key('user_contact_user_id_fkey', 'user_contact', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'booking_id')
    op.drop_constraint(None, 'catering_menu_item', type_='foreignkey')
    op.drop_constraint(None, 'catering_menu_item', type_='foreignkey')
    op.create_foreign_key('catering_menu_item_catering_id_fkey', 'catering_menu_item', 'catering', ['catering_id'], ['catering_id'])
    op.create_foreign_key('catering_menu_item_dish_id_fkey', 'catering_menu_item', 'dish', ['dish_id'], ['dish_id'])
    op.drop_constraint(None, 'car_reservation', type_='foreignkey')
    op.drop_constraint(None, 'car_reservation', type_='foreignkey')
    op.create_foreign_key('car_reservation_car_id_fkey', 'car_reservation', 'car', ['car_id'], ['car_id'])
    op.create_foreign_key('car_reservation_booking_id_fkey', 'car_reservation', 'booking', ['booking_id'], ['booking_id'])
    op.add_column('booking', sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key('booking_user_id_fkey', 'booking', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key('booking_catering_id_fkey', 'booking', 'catering', ['catering_id'], ['catering_id'])
    op.create_foreign_key('booking_payment_id_fkey', 'booking', 'payment', ['payment_id'], ['payment_id'])
    op.create_foreign_key('booking_promo_id_fkey', 'booking', 'promo', ['promo_id'], ['promo_id'])
    op.create_foreign_key('booking_decoration_id_fkey', 'booking', 'decoration', ['decoration_id'], ['decoration_id'])
    # ### end Alembic commands ###
