import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Inter } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../theme";
import { CssBaseline } from "@mui/material";
import { QueryProvider } from "@/QueryProvider";

const inter = Inter({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ` + inter.variable}>
        <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <CssBaseline />
          <QueryProvider>
              {children}
          </QueryProvider>
            </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
